#!/usr/bin/env python3
"""将JSON格式Cookie转换为Netscape格式（yt-dlp期望的格式）"""

import json
from pathlib import Path


def convert_json_to_netscape(json_file: str, netscape_file: str):
    """将JSON格式Cookie转换为Netscape格式"""
    # 读取JSON Cookie
    with open(json_file, "r", encoding="utf-8") as f:
        cookies = json.load(f)
    
    # 写入Netscape格式
    with open(netscape_file, "w", encoding="utf-8") as f:
        f.write("# Netscape HTTP Cookie File\n")
        f.write("# This file was generated by bilibili_cookie_manager.py\n")
        f.write("# Usage: yt-dlp --cookies cookies.txt\n")
        f.write("\n")
        
        # B站Cookie的域名
        domains = [
            (".bilibili.com", "TRUE"),
            ("www.bilibili.com", "FALSE"),
        ]
        
        for key, value in cookies.items():
            # 选择合适的域名
            domain = ".bilibili.com"  # 默认使用泛域名
            secure = "FALSE"
            expiration = "0"  # 会话Cookie
            
            f.write(f"{domain}\t{secure}\t/\tFALSE\t{expiration}\t{key}\t{value}\n")
    
    print(f"✅ 已转换 {len(cookies)} 个Cookie到Netscape格式：{netscape_file}")


if __name__ == "__main__":
    json_file = "config/bilibili_cookies.json"
    netscape_file = "config/bilibili_cookies.txt"
    
    convert_json_to_netscape(json_file, netscape_file)
